age<-c(5,6,7)
name<-c("james","john","adam")
friends<-data.frame(age,name)
View(friends)
install.packages("tidyverse")
library("tidyverse")

data()
View(starwars)
glimpse(starwars)
head(starwars)
class(starwars$mass)
unique(starwars$mass)
missing<-!complete.cases(starwars)
View(missing)
View(msleep)
str(starwars)
typeof(starwars)
typeof(msleep)
class(starwars)
class(msleep)
class(starwars$name)
distinct(starwars$mass)
df<-data.frame(starwars$name, starwars$mass)
View(df)
str(df)
distinct(df)
df1<-starwars[,c("name","mass")]
View(df1)
library(dplyr)
library(gapminder)
View(gapminder)
gap2<-select(gapminder,country,continent,pop)
View(gap2)
wide_data<-select(gapminder,country,year,lifeExp)%>%
  pivot_wider(names_from=year, values_from=lifeExp)
View(wide_data)
min(starwars$height)
msleep%>%
  select(vore,order)%>%
  filter(order %in% c("Rodentia","Primates"))%>%
  table()
View(gapminder)
t_test_plot
attributes(starwars)
